### ISSUE TITLE
Pełny przebieg walki

### ISSUE THREAD

**Issue by Michal-Czekanski** [emkarcinos/WMIAdventure#613]
branch `feat_full_battle_process`

Pełna implementacja przebiegu walki na backendzie:
- [x] #248 zrobić tak żeby dało się ten przebieg zserializować (być może trzeba zmodyfikować jakoś battle recorder, czy tam inne klasy, nie pamiętam już?)
- [x] #206 stworzyć serializer przebiegu walki
- [x] #207 wystawić widok/i pozwalające na odebranie danych o tymże przebiegu walki
